package com.fps.datagen.pokemon

import Pokemon._

/* @author medge */

object Generations {
  val Generation1 = Set(
    Bulbasaur, Ivysaur, Venusaur,
    Charmander, Charmeleon, Charizard,
    Squirtle, Wartortle, Blastoise,
    Caterpie, Metapod, Butterfree,
    Weedle, Kakuna, Beedrill,
    Pidgey, Pidgeotto, Pidgeot,
    Rattata, Raticate,
    Spearow, Fearow,
    Ekans, Arbok,
    Pikachu, Raichu,
    Sandshrew, Sandslash,
    NidoranF, Nidorina, Nidoqueen,
    NidoranM, Nidorino, Nidoking,
    Clefairy, Clefable,
    Vulpix, Ninetails,
    Jigglypuff, Wigglytuff,
    Zubat, Golbat,
    Oddish, Gloom, Vileplume,
    Paras, Parasect,
    Venonat, Venomoth,
    Diglett, Dugtrio,
    Meowth, Persian,
    Psyduck, Golduck,
    Mankey, Primeape,
    Growlithe, Arcanine,
    Poliwag, Poliwhirl, Poliwrath,
    Abra, Kadabra, Alakazam,
    Machop, Machoke, Machamp,
    Bellsprout, Weepinbell, Victreebel,
    Tentacool, Tentacool,
    Geodude, Graveler, Golem,
    Ponyta, Rapidash,
    Slowpoke, Slowbro,
    Magnemite, Magneton,
    Farfetchd,
    Doduo, Dodrio,
    Seel, Dewgong,
    Grimer, Muk,
    Shelder, Cloyster,
    Gastly, Haunter, Gengar,
    Onix,
    Drowzee, Hypno,
    Krabby, Kingler,
    Voltorb, Electrode,
    Exeggcute, Exeggutor,
    Cubone, Marowak,
    Hitmonlee,
    Hitmonchan,
    Lickitung,
    Koffing, Weezing,
    Rhyhorn, Rhydon,
    Chansey,
    Tangela,
    Kangaskhan,
    Horsea, Seadra,
    Goldeen, Seaking,
    Staryu, Starmie,
    MrMime,
    Scyther,
    Jynx,
    Electabuzz,
    Magmar,
    Pinsir,
    Tauros,
    Magikarp, Gyarados,
    Lapras,
    Ditto,
    Eevee, Vaporeon, Jolteon, Flareon,
    Porygon,
    Omanyte, Omastar,
    Kabuto, Kabutops,
    Aerodactyl,
    Snorlax,
    Articuno,
    Zapdos,
    Moltres,
    Dratini, Dragonair, Dragonite,
    Mewtwo,
    Mew
  )

}
